### PR TITLE
Testing without the GitHub Action

### PR DESCRIPTION
**Pull request by sean-treanor**

### CODE REVIEW

**Review by daughey — APPROVED** [review]
Looks good

**Review by seminautesman-7245 — APPROVED** [review]
I approve.

**Review by AnnaK210 — APPROVED** [review]

**Review by daughey — CHANGES_REQUESTED** [review]
changed my mind

**Review by seminautesman-7245 — APPROVED** [review]
I approve.

**Review by seminautesman-7245 — APPROVED** [review]
I approve for the third time.

**Pull request closed without merging**
